server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atendimento?createDatabaseIfNotExist=true&
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

